### ISSUE TITLE
Assert css variable value?

### ISSUE THREAD

**Issue by jkeen** [mainmatter/qunit-dom#1972]
It doesn't seem like qunit-dom has the ability to check the value of a css custom property/variable, like `--color-text`, or whatever. Am I right about that?

I tried using `hasStyle`, `hasAttribute`, and `hasProperty` with no avail. In trying to make some changes for a PR, but it seems ilke the issue might be a jest / node thing?

**Comment by BobrImperator** [comment]
With #1976 merged it might've been fixed, at least for the `hasStyle` test.

Feel free to reopen if it's not fixed.
