### ISSUE TITLE
Types - Interface Assert, `rootElement` should also be `null`

### ISSUE THREAD

**Issue by MrChocolatine** [mainmatter/qunit-dom#882]
Current signature of the method `dom()`:
https://github.com/simplabs/qunit-dom/blob/6c31d65d825c8c09fab1c4f604b8a89945c06e11/lib/qunit-dom.ts#L10

But it is not completely accurate and triggers an error when `rootElement` comes from a basic `querySelector()`:
```js
const myTable = this.element.querySelector(/* my-selector */)
assert.dom('tbody > tr', myTable).exists({ count: 2 })
// -------------------------^
// const myTable: Element | null
// Argument of type 'Element | null' is not assignable to parameter of type 'Element | undefined'.
//   Type 'null' is not assignable to type 'Element | undefined'.
```

`rootElement` should also be accepted as `null`:

```TypeScript
 dom(target?: string | Element | null, rootElement?: Element | null): DOMAssertions; 
```

**Comment by Turbo87** [comment]
hmm... I'm not sure I agree. If that `querySelector()` call returned `null` then what would you expect would happen?

Passing in an element will use that element as the root element. Not passing in anything should default to using the default root element. But explicitly passing in `undefined` or `null` seems like a bug to me, no?

**Comment by MrChocolatine** [comment]
I kind of agree @Turbo87 but not entirely.

> hmm... I'm not sure I agree. If that querySelector() call returned null then what would you expect would happen?

Nothing. The same that would happen with `undefined`.

In an other hand why should we have to do this every time to specifically match with the signature?
Seems like a bit tedious to me.

```TypeScript
const myTable = this.element.querySelector(/* my-selector */)
assert.dom('tbody > tr', myTable || undefined).exists({ count: 2 })
```

The thing is, it is literally the pure and basic types returned from `querySelector()`, `getElementById()` and every other method to target a DOM element.

**Comment by MrChocolatine** [comment]
Any update on this please :)?

The type returned by `querySelector()` being `Element | null` (like many other DOM methods), it does not match the types of the second argument `rootElement` of `assert.dom()`.

> But explicitly passing in undefined or null seems like a bug to me, no?

Even if, in the context of a test, we know our element should exist me might have made a mistake in the selector and `null` would be implicitly returned (so the default root element will be used), we should not have to do anything more with the following code:

```TypeScript
const myElem = this.element.querySelector(/* my-selector */)
assert.dom('.some-class', myElem).exists({ count: 2 })
```
